export const loremIpsum = `
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer bibendum quam justo, ac tincidunt ex varius at. Maecenas vitae sapien sit amet enim varius pretium at id dolor. Praesent pellentesque turpis quis rutrum tempus. Integer condimentum lorem in dolor iaculis, eget viverra eros feugiat. Morbi nec sollicitudin lectus. Phasellus mollis ex id egestas convallis. Nulla porttitor vel lacus non fermentum. Pellentesque condimentum tempor turpis et congue. Maecenas sit amet odio vitae mauris congue suscipit. Donec vel ante quis nunc commodo consequat. Quisque vel ullamcorper nisi, quis tempus est. Mauris vitae interdum massa.

Fusce condimentum aliquet nisi vitae pretium. Etiam eu metus nibh. Curabitur accumsan et nulla nec condimentum. Praesent risus risus, vehicula in lobortis nec, laoreet eget elit. Cras dictum fermentum justo eu sodales. Sed orci lectus, elementum a lacus et, interdum tincidunt erat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In congue eleifend dignissim. Proin augue libero, rutrum quis molestie non, interdum nec nisi. Cras massa diam, convallis sed dictum eu, aliquet vel purus. Phasellus erat eros, dignissim sed vulputate eu, venenatis ut dolor. Nullam condimentum rutrum ipsum, vitae viverra nisi ultricies sed. Suspendisse potenti. Cras luctus feugiat elit sagittis ultricies. Sed lectus neque, lobortis eu elit ut, maximus mattis purus. Sed sodales erat a nibh pharetra, ac luctus sem aliquam.

Morbi lorem ex, pellentesque eu luctus vitae, dapibus eu dui. Phasellus nibh nisi, lacinia eu nibh sit amet, porta finibus urna. Vestibulum tempus sapien risus, at rutrum libero rutrum non. Aliquam ut aliquam dui. Ut a eros ligula. Nulla a lacus eu est tempor pellentesque. Curabitur hendrerit justo placerat finibus vehicula.

In tristique, velit sodales fringilla consequat, felis dolor eleifend quam, porttitor consectetur purus turpis eget magna. Mauris et efficitur tellus. Vivamus nec mollis lectus. Donec et ante non lacus lacinia tincidunt quis id dui. Etiam orci nisi, pulvinar ac nisi ac, vulputate tincidunt massa. Aenean tristique purus eu metus feugiat fringilla. Vestibulum ac metus nulla. Morbi id ante sit amet eros volutpat condimentum. Proin gravida turpis tortor, vitae faucibus velit luctus quis.

Donec mi urna, vulputate ac ipsum id, rhoncus aliquam leo. Mauris nec mollis massa, in accumsan felis. Vestibulum posuere, velit sed efficitur pellentesque, purus nisi vulputate sapien, ac ultricies justo felis ut arcu. Etiam finibus ante nec quam pretium condimentum. Vivamus nec pulvinar mauris. Morbi quis egestas augue, vitae viverra erat. Aliquam lacus libero, imperdiet non condimentum vitae, tincidunt quis tellus. Donec at orci mauris. Donec commodo tempor fermentum. Sed ullamcorper ante sit amet eros ultricies faucibus. Proin euismod nulla at eros feugiat, ut dictum mi accumsan. Suspendisse risus leo, cursus a purus vestibulum, sagittis pellentesque urna. Donec vitae enim velit. Nam sodales tristique sapien eu elementum.
`;
